FROM node:22-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install -g @angular/cli@20.3
RUN npm install
RUN npm install --save-dev body-parser  # ← Ajoutez cette ligne
COPY --from=builder /app/dist/frontend/browser /usr/share/nginx/html
EXPOSE 4200
CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200", "--proxy-config", "proxy.conf.js"]
