FROM node:22-alpine

# Installer Angular CLI version 20.3
RUN npm install -g @angular/cli@20.3

# Désactiver l'analytics
RUN ng analytics off --global

WORKDIR /app

# Copier package.json et installer les dépendances
COPY package*.json ./
RUN npm install

# 🔥 Ne pas copier le code ni builder ici, il sera monté via volume

EXPOSE 4200

# 🔥 Pas de CMD ici, il est dans docker-compose
