FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install -g @angular/cli@20.3
RUN npm install
RUN npm install --save-dev body-parser  # ← Ajoutez cette ligne
RUN apk add --no-cache chromium
ENV CHROME_BIN=/usr/bin/chromium-browser
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
COPY . .
RUN mkdir -p /var/log/trinity
EXPOSE 4200
CMD ["sh", "-c", "STAMP=$(date +'%d-%m-%Y-%H-%M'); LOG_FILE=/var/log/trinity/frontend_${STAMP}.log; touch \"$LOG_FILE\"; ln -sf \"$LOG_FILE\" /var/log/trinity/frontend.log; ng serve --host 0.0.0.0 --port 4200 --proxy-config proxy.conf.js 2>&1 | tee -a \"$LOG_FILE\""]
