server {
    listen 80;
    server_name localhost;

    # Répertoire par défaut pour Angular
    root /usr/share/nginx/html;
    index index.html;

    # --- Serve Compodoc documentation ---
    location /docs/ {
        alias /usr/share/nginx/html/docs/;
        index index.html;
        try_files $uri $uri/ =404;
    }

    # --- Proxy GraphQL Login ---
    location /graphql-login/ {
        proxy_pass http://django_backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Cookie $http_cookie;
        proxy_redirect off;
    }

    # --- Proxy GraphQL ---
    location /graphql/ {
        proxy_pass http://django_backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Cookie $http_cookie;
        proxy_redirect off;
    }

    # --- Angular app (SPA fallback) ---
    location / {
        try_files $uri /index.html;
    }
}
