services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mydb}
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-myuser}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
          #commande pour hotreload
      dockerfile: Dockerfile.dev
    container_name: django_backend
    #commande pour hotreload
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - /app/venv
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./frontend
          #commande pour hotreload
      dockerfile: Dockerfile.dev
    container_name: angular_frontend
    #commande pour hotreload
    command: ng serve --host 0.0.0.0 --port 4200 --poll 2000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.angular
    ports:
      - "4200:4200"
    environment:
      NG_CACHE: /tmp/.angular/cache
    depends_on:
      - backend
    stdin_open: true
    tty: true