# Generated by Django 4.2.25 on 2025-10-08 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=100)),
                ('telephone', models.IntegerField()),
                ('mot_de_passe', models.TextField(max_length=100)),
                ('role', models.TextField(max_length=100)),
                ('id_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trinity.team')),
            ],
        ),
        migrations.CreateModel(
            name='Calendrier',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('type_journee', models.TextField(max_length=100)),
                ('id_employee', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='trinity.user')),
            ],
        ),
    ]
