# Generated by Django 4.2.25 on 2025-10-08 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trinity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id_team',
            new_name='team',
        ),
    ]
