# Generated by Django 4.2.25 on 2025-10-09 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trinity', '0002_rename_id_team_user_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendrier',
            old_name='id_employee',
            new_name='employee',
        ),
        migrations.AlterField(
            model_name='user',
            name='mot_de_passe',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='trinity.team'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(max_length=100),
        ),
    ]
