# Generated by Django 4.2.25 on 2025-10-09 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trinity', '0003_rename_id_employee_calendrier_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='trinity.team'),
        ),
    ]
