# Generated by Django 4.2.25 on 2025-10-24 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trinity', '0003_event_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='field',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='trinity.team'),
        ),
    ]
