# Generated by Django 4.2.25 on 2025-10-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trinity', '0004_team_field_alter_user_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
