# Generated by Django 4.2.27 on 2025-12-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trinity', '0005_alter_team_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='annual_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='contract',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='leaves',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='social_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
