# Generated by Django 4.2.27 on 2025-12-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trinity', '0006_user_annual_salary_user_arrival_date_user_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='working_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
