# Generated by Django 4.2.27 on 2025-12-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trinity', '0007_user_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='social_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
